### ISSUE TITLE
 Code Implementation

### ISSUE THREAD

**Issue by ChayaEstherLangsner** [ChayaEstherLangsner/memory#3]

**Comment by AshiraFriedman** [comment]
When I try to run the game, it crashes.  Is it working on your computer?
It doesn't seem that the picture files are included in your project.  They seem to be in a folder outside the project.  
You can review the video in the session which explains how to include images in your project properly.
Let me know when this is fixed.

**Comment by AshiraFriedman** [comment]
Is there a reason that the images are not just in a regular folder titled "images"?  Why are there so many subfolders to get to the images?
Also, is it working for you when you run it?
It still is not recognzing the images - it shows that they are not included in source control.  Are you having the same problem?  If it's working for you, maybe there is something wrong with my settings and I can try troubleshooting it.

**Comment by ChayaEstherLangsner** [comment]
It works for me and the reason why I saved the pics in that folder is cause that where this code leads you to 
System.Windows.Forms.Application.StartupPath

**Comment by AshiraFriedman** [comment]
I figured out why I was having a problem running the project.  
The pics folder is  in the bin folder, and the bin folder is ignored with the gitignore file being used.  So, the files were ignored and I never had access to them, they were never pushed to your remote.
I need you to take them out of that directory, and just create a regular folder called pics or images, not in that long path.  There is no need to put the folder in that long path.  You can watch the video,no need to specify that long directory of subfolders.
Remember to set the images with the right properties if you haven't yet - 
Set image properties:
a.Copy to Output Directory = Copy Always
b.Build Action = Content
Sorry if this was confusing, let me know if you need help.

**Comment by AshiraFriedman** [comment]
Wow! Amazing job!
The UI looks very nice and the game is working nicely!
I like the popup messages when needed.
Nice pics with the images, theyre very cute.
I did QA and one thing needs to be fixed.
There's a weird behavior - when the user gets a match, those boxes disappear and all the boxes after it change position and shift one to the left, taking the place of the match picked.   Please fix this and let me know.

**Comment by AshiraFriedman** [comment]
Creative way to make that fix!
I did a code review, fantastic job!!  Very impressive work, it's well written, clear and concise
Please see a few comments and resubmit.

**Comment by AshiraFriedman** [comment]
Fantastic job!
